[tool.poetry]
name = "eddie-cli"
version = "0.1.0"
description = "Eddie — The AI-powered CLI Assistant"
authors = ["William Bakst <william@mirascope.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.scripts]
eddie = "eddie_cli.main:app"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
typer = "^0.12.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
